### ISSUE TITLE
Adding multiple wall textures

### ISSUE THREAD

**Issue by ronnie-dumesh** [foxhatleo/fallen-flame-level-editor#2]
Due to some changes, we have two different wall-textures now. Would it be possible to update the wall textures in the actual level editor and make two seperate wall components? One texture is titled "single-brick" and the other is "double-brick". 
![image](https://user-images.githubusercontent.com/43655768/78931195-8d611900-7a73-11ea-98a4-14b305efba09.png)

**Comment by ronnie-dumesh** [comment]
The circled ones are "single-bricks", the other ones are "double-bricks"

**Comment by BryanGraeser** [comment]
Question/potential issue: Should the player collide with the bottom of that texture? Because then the player can't get very close to the wall. They will likely need to be able to overlap. For example in this image, the character on the right is standing in front of and close to the houses' wall so they are drawn over it:
![image](https://user-images.githubusercontent.com/33598616/78935666-0788a200-7a62-11ea-915f-c4b1ffc46496.png)
Source: https://forum.unity.com/attachments/upload_2019-8-14_12-51-14-png.467513/

**Comment by BryanGraeser** [comment]
I think the best thing to do would just be to have the collision body of the player only be the base of the player, so the player can partially overlap with the wall, but once their "Shadow" touches the wall, they can't move farther. You can see the character on the right's shadow does not overlap with the wall.

**So in short, make sure the player's collision body is their shadow**

**Comment by BryanGraeser** [comment]
Another thing we could do is split the texture into two parts where one is an actual wall with collision and physics, and the other is just a texture with no collisions.

For example with the single brick wall:
![single-brick](https://user-images.githubusercontent.com/33598616/78936283-2176b480-7a63-11ea-9546-85d8a57a5597.png)

we can split into two parts, the top:
![single-brick-top](https://user-images.githubusercontent.com/33598616/78936291-29ceef80-7a63-11ea-877e-b3ee6606e8fb.png)

and the bottom: 
![single-brick-bottom](https://user-images.githubusercontent.com/33598616/78936303-2e93a380-7a63-11ea-8c2e-a994391d26d9.png)

The top would be a normal wall with collisions so the player cannot overlap with it at all. Meanwhile the bottom would not have any collisions so the player could overlap with it completely. Then in the level editor you could just place tops and bottoms separately.

**But this is very hacky, so I don't think we should pursue this.**

**Comment by ronnie-dumesh** [comment]
The new wall objects are actually called "vertical-wall" and "horizontal-wall" in the JSON I apologize for the confusion.

**Comment by ronnie-dumesh** [comment]
I think we have more pressing priorities than fixing this. People can manually change the wall texture names, not super important anyway.
